name: cron-build

on:
  schedule:
    - cron: "*/60 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Container
        uses: timzu/docker-builder@master

      - name: Check Versions
        run: |
          bash ./check.sh

      - name: Commit & Push
        uses: timzu/github-actions-build@master
        with:
          args: --commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE_PATH: ./target/message.txt
          GIT_BRANCH: main
