name: cron-push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Container
        uses: timzu/docker-builder@master

      - name: Check
        run: |
          bash ./check.sh

      - name: Commit & Push
        uses: timzu/github-actions-build@master
        with:
          args: --commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE_PATH: ./target/message.txt
          GIT_BRANCH: main

      - name: Release
        uses: timzu/github-actions-build@master
        with:
          args: --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
